### ISSUE TITLE
3 unavailable videos are hidden

### ISSUE THREAD

**Issue by codycode** [slackapi/node-tasks-app#92]
### Is there an existing issue for this?

- [X] I have searched for any related issues and avoided creating a duplicate issue.

### Have you read our code of conduct?

- [X] I have read and agree to the code of conduct

### Current Behavior

The accompanying video series has 3 of the 7 videos set as private.

https://www.youtube.com/playlist?list=PLWlXaxtQ7fUb0B4uNTKirvrQ0JOTCBFae

### Expected Behavior

There is a 7-part video series that accompanies this repo.

### Steps To Reproduce

Go to https://www.youtube.com/playlist?list=PLWlXaxtQ7fUb0B4uNTKirvrQ0JOTCBFae

### Environment

```markdown
- OS: All
- Language version: All
```

**Comment by colmdoyle** [comment]
That's so weird, I don't know how that happened, but we've fixed it now, thanks for letting us know!
